<a href="https://colab.research.google.com/github/sevval-345/SoftITo/blob/main/HABERSENT%C4%B0MENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk

nltk.download('vader_lexicon')

ticker = "İran"  # arama terimi olarak kullanılacak

# Google News RSS - tamamen ücretsiz, API yok
url = f"https://news.google.com/rss/search?q={ticker}&hl=en&gl=US&ceid=US:en"

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
response = requests.get(url, headers=headers)

parser = BeautifulSoup(response.text, "xml")
items = parser.find_all("item")

sia = SentimentIntensityAnalyzer()
sentiments = []

for item in items:
    title = item.find("title").text
    pub_date = item.find("pubDate").text[:16]  # tarih kısmı
    source = item.find("source").text if item.find("source") else "unknown"
    link = item.find("link").text

    score = sia.polarity_scores(title)

    sentiments.append({
        "ticker": ticker,
        "date": pub_date,
        "source": source,       # hangi haber sitesi
        "title": title,
        "compound": score["compound"],
        "positive": score["pos"],
        "negative": score["neg"],
        "neutral":  score["neu"]
    })

df = pd.DataFrame(sentiments)
df = df.set_index("date")

print(df[["ticker", "source", "title", "compound"]].to_string())

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

                 ticker                           source                                                                                                                                 title  compound
date
Sat, 23 May 2026   İran                       Al Jazeera                                                   Iran war live: Tehran says diplomacy continues but no deal yet with US - Al Jazeera   -0.6428
Sat, 23 May 2026   İran               The New York Times                                            Once Trump’s Co-Pilot Against Iran, Netanyahu Is Now a Mere Passenger - The New York Times    0.0000
Sat, 23 May 2026   İran                         Fox News                                 Renewed US combat operations against Iran are ‘matter of when,' former Navy commander says - Fox News   -0.3400
Sat, 23 May 2026   İran                         Sky News               Iran war latest: Trump says Iran war will be 'over with soon' - as US national intelligence director resigns - Sky News   -0.7906
Sat, 23 May 2026   İran              The Times of Israel  Over 1.5 million pilgrims join Hajj despite flight disruptions from Iran war, Tehran's attacks on Saudi Arabia - The Times of Israel   -0.5520
Sat, 23 May 2026   İran                              WSJ                                                                  How the War in Iran Helped Ukraine Go From Problem to Solution - WSJ   -0.6486
Sat, 23 May 2026   İran                              CNN                                                    Trump meets with national security officials as he weighs next steps on Iran - CNN    0.3400
Fri, 22 May 2026   İran                         CBS News                                                                        U.S. prepares for new military strikes against Iran - CBS News   -0.3612
Sat, 23 May 2026   İran                              BBC                                                              Marco Rubio visits India to sell energy as Iran oil shock persists - BBC   -0.1280
Sat, 23 May 2026   İran                          Reuters                                                                              Three months in, is Trump losing the Iran war? - Reuters   -0.7579
Fri, 22 May 2026   İran   Institute for the Study of War                                                             Iran Update Special Report, May 22, 2026 - Institute for the Study of War   -0.2960
Sat, 23 May 2026   İran                 ایران اینترنشنال                                    Live - Iran downplays deal hopes as Pakistan pushes talks and US weighs strikes - ایران اینترنشنال    0.0772
Sat, 23 May 2026   İran               The New York Times                                                       The Risks of Iran’s Threat to Control the Strait of Hormuz - The New York Times   -0.6705
Sat, 23 May 2026   İran                         The Week                                                                                The war with Iran: stalemate, or checkmate? - The Week   -0.5994
Sat, 23 May 2026   İran               The Jerusalem Post                                                          Live Updates: Latest from Israel, Iran, and Middle East - The Jerusalem Post    0.0000
Sat, 23 May 2026   İran                     The Guardian               An ever-expanding catastrophe over Iran is not inevitable. Trump can and must be stopped | Simon Tisdall - The Guardian   -0.7430
Fri, 22 May 2026   İran                              WSJ                                                                                     Opinion | Don’t Leave the Iran War Half-Won - WSJ   -0.6249
Sat, 23 May 2026   İran                       Al Jazeera                                                               Iran war day 85: Tehran says major gaps remain in US talks - Al Jazeera   -0.5994
Sat, 23 May 2026   İran                 ایران اینترنشنال                                                          Hope for US-Iran deal faces hardliner hostility in Tehran - ایران اینترنشنال   -0.1531
Sat, 23 May 2026   İran               The New York Times                                                             Regional Mediators Rush to Save U.S.-Iran Cease-Fire - The New York Times    0.4939
Sat, 23 May 2026   İran               The New York Times                                                     Trump Weighs His Options in Carrying Out New Strikes in Iran - The New York Times   -0.3612
Fri, 22 May 2026   İran                              PBS                                        U.S. says 'slight progress' in Iran talks amid uncertainty about whether war will resume - PBS   -0.5423
Sat, 23 May 2026   İran                       Al Jazeera                                               Iran weighs US peace proposal despite ‘deep and significant’ disagreements - Al Jazeera    0.1779
Sat, 23 May 2026   İran                    Bloomberg.com                                                                           What If the Strait of Hormuz Didn’t Reopen? - Bloomberg.com    0.0000
Sat, 23 May 2026   İran               Hasht-e Subh Daily                                                                Iran–US Tensions; Asim Munir meets Abbas Araghchi - Hasht-e Subh Daily   -0.4019
Sat, 23 May 2026   İran                              WSJ                                                   Iran Moved Billions Through Binance to Fund Regime—Continuing Into This Month - WSJ    0.0000
Fri, 22 May 2026   İran                            Axios                                                                     Trump met top advisers on Iran as he weighs return to war - Axios   -0.4767
Fri, 22 May 2026   İran                            Axios                                                               Pakistani field marshal in Tehran to try to seal U.S.-Iran deal - Axios    0.0000
Fri, 22 May 2026   İran                       Al Jazeera                                                             Economic confidence plummets in US amid Iran war, poll shows - Al Jazeera   -0.1531
Sat, 23 May 2026   İran                          Reuters                                                                  US arms sales to Taiwan unrelated to Iran war, source says - Reuters   -0.5994
Sat, 23 May 2026   İran              The Times of Israel                              Trump reportedly moving toward ordering strikes on Iran but no final decision made - The Times of Israel   -0.5499
Fri, 22 May 2026   İran                          AP News                            Rubio reports 'slight progress' in Iran talks as Pakistan renews efforts to mediate a peace deal - AP News    0.7430
Sat, 23 May 2026   İran                          Reuters                                                           Indian retailers raise fuel prices for a third time amid Iran war - Reuters   -0.5994
Sat, 23 May 2026   İran                   Anadolu Ajansı                                      US weighs renewed military action against Iran as negotiations continue: Report - Anadolu Ajansı    0.0000
Thu, 21 May 2026   İran   Institute for the Study of War                                                             Iran Update Special Report, May 21, 2026 - Institute for the Study of War   -0.2960
Fri, 22 May 2026   İran               The Jerusalem Post                No deal in sight if US insists on discussing nuclear issue, Iranian FM spokesperson says - report - The Jerusalem Post   -0.2960
Thu, 21 May 2026   İran     Council on Foreign Relations                                 Iran’s War With Israel and the United States | Global Conflict Tracker - Council on Foreign Relations   -0.5267
Thu, 21 May 2026   İran                              WSJ                                                                             Opinion | The Iran War and the Anti-American Reflex - WSJ   -0.5994
Fri, 22 May 2026   İran                          Reuters                     Exclusive: Qatari negotiating team in Tehran to try to help secure US-Iran deal to end war, says source - Reuters    0.1779
Sat, 23 May 2026   İran                   Anadolu Ajansı                                              Iranian top diplomat, Pakistan army chief discuss US-Iran peace efforts - Anadolu Ajansı    0.6486
Fri, 22 May 2026   İran                       Al Jazeera                                              Pakistan’s army chief in Iran as US’s Rubio says ‘slight progress’ in talks - Al Jazeera    0.0000
Fri, 22 May 2026   İran                          Reuters                                             Iran's intensified closure of Strait of Hormuz piles misery on stranded sailors - Reuters   -0.5719
Fri, 22 May 2026   İran                         ynetnews                                        Last-ditch push before war? Iran talks near collapse as Trump weighs a final strike - ynetnews   -0.8225
Sat, 23 May 2026   İran                 RealClearDefense                                                                                   Don’t Repeat Afghanistan in Iran - RealClearDefense    0.0000
Fri, 22 May 2026   İran                         The Hill                                                                    Iran, Oman discuss Strait of Hormuz toll system: Report - The Hill    0.0000
Thu, 21 May 2026   İran                         CBS News                             Iran says it's mulling latest U.S. peace proposal and Trump says he'll wait "a couple of days" - CBS News    0.5423
Fri, 22 May 2026   İran                          AP News                                Photos of live music stirring back to life in Tehran as a ceasefire offers a fragile respite - AP News    0.0000
Fri, 22 May 2026   İran                              WSJ                                                             The Oil Mystery at the Heart of America’s Pressure Campaign on Iran - WSJ   -0.2960
Sat, 23 May 2026   İran                    Bloomberg.com                                                           Iran Peace Deal Push Intensifies as Fragile Ceasefire Holds - Bloomberg.com    0.5423
Fri, 22 May 2026   İran                         Fox News                                               Top Republican warns Trump against making a deal with Iran: 'Finish the job' - Fox News    0.1027
Fri, 22 May 2026   İran                             CNBC                            U.S., Iran signal peace progress — but remain at odds over enriched uranium, Strait of Hormuz tolls - CNBC    0.4854
Fri, 22 May 2026   İran                         ynetnews                                                              Report: 'Trump administration preparing to strike Iran again' - ynetnews   -0.1280
Thu, 21 May 2026   İran                         NBC News                              Iran-U.S. diplomacy intensifies as Trump seeks ‘right answers,’ Tehran signals gaps ‘reduced’ - NBC News    0.0000
Thu, 21 May 2026   İran                    economist.com                                                                 Donald Trump is still looking for a quick fix in Iran - economist.com    0.0000
Fri, 22 May 2026   İran              The Times of Israel                           Qatari team in Tehran for talks; Trump says skipping son’s wedding to stay in capital - The Times of Israel    0.0000
Fri, 22 May 2026   İran                         The Hill                                       Wicker warns Trump against ‘ill advised’ Iran deal: ‘We must finish what we started’ - The Hill   -0.1027
Fri, 22 May 2026   İran               The New York Times                                                      Asian Currencies Hit by Iran War, Adding to Economic Strain - The New York Times   -0.6249
Thu, 21 May 2026   İran                          Reuters                                      Exclusive: Supreme Leader says enriched uranium must stay in Iran, Iranian sources say - Reuters    0.6249
Fri, 22 May 2026   İran                         NBC News                                                                        House Republicans cancel vote curbing Trump on Iran - NBC News   -0.2500
Fri, 22 May 2026   İran                  Middle East Eye                                                   Iran destroyed 20 percent of US's MQ-9 Reaper drone fleet: Report - Middle East Eye   -0.4939
Sat, 23 May 2026   İran        Robin J Brooks | Substack                                                                   The US Blockade of Iran after Six Weeks - Robin J Brooks | Substack    0.0000
Fri, 22 May 2026   İran                         CBS News                                                 Gabbard resignation comes as Trump may be considering relaunching Iran war - CBS News   -0.7269
Sat, 23 May 2026   İran                           DW.com                                                                          US or Iran: Who will win the Hormuz endurance game? - DW.com    0.5859
Sat, 23 May 2026   İran                 ایران اینترنشنال                                                      Iran cleric says hijab should not divide wartime mobilization - ایران اینترنشنال    0.0000
Fri, 22 May 2026   İran                          Reuters                                               US Secretary of State Rubio sees progress in Iran talks, more work to be done - Reuters    0.4215
Fri, 22 May 2026   İran                              NPR                                               Republicans call off vote on Iran war resolution that was on the verge of passing - NPR   -0.5994
Fri, 22 May 2026   İran              The Washington Post                                          Opinion | I did something AI never could: Make my calculus teacher cry - The Washington Post   -0.4767
Fri, 22 May 2026   İran                              PBS                                                                          Is it time for the U.S. to reassess its Iran strategy? - PBS    0.0000
Fri, 22 May 2026   İran                             CNBC                                                     Oil prices post weekly loss as U.S. and Iran signal progress toward a deal - CNBC    0.1280
Fri, 22 May 2026   İran                             CNBC                                            Consumer sentiment hits fresh record low in May as Iran war fuels inflation worries - CNBC   -0.7579
Thu, 21 May 2026   İran               The New York Times                                      GOP Pulls Measure on Trump’s War Powers in Iran, Lacking Votes to Defeat It - The New York Times   -0.7845
Sat, 23 May 2026   İran                        France 24                                                                        War in the Middle East: US-Iran talks make headway - France 24   -0.5994
Fri, 22 May 2026   İran               The New York Times                                                 Iran and Oman in Talks Over Strait of Hormuz Ship Payment System - The New York Times    0.0000
Fri, 22 May 2026   İran                         The Hill                                                                              Bolton pushes for Trump to end Iran ceasefire - The Hill    0.0000
Sat, 23 May 2026   İran               The Jerusalem Post                Iran, Oman negotiate possible tolls system for Strait of Hormuz even as US warns against it - NYT - The Jerusalem Post   -0.1027
Sat, 23 May 2026   İran                    Bloomberg.com                                                          Arab Nations Seek Iran War Deal as Ceasefire Remains Fragile - Bloomberg.com   -0.5994
Fri, 22 May 2026   İran                        France 24                                                            Rubio urges more support from NATO allies to help end Iran war - France 24    0.2006
Thu, 21 May 2026   İran                             CNBC                                                                           Oil prices fall as investors hope for U.S.-Iran deal - CNBC    0.4404
Fri, 22 May 2026   İran                    Bloomberg.com                                                            UAE Joins Saudis, Qatar in Urging Trump Not to Restart War - Bloomberg.com    0.4847
Sat, 23 May 2026   İran                           Forbes                                                         Trump’s Approval Rating Declines In 4 Polls This Week, Improves In 1 - Forbes    0.7096
Thu, 21 May 2026   İran                              BBC                                                           Strait of Hormuz: Iran steps up claim to control Middle East waterway - BBC    0.0000
Fri, 22 May 2026   İran                       Al Jazeera                                                         Iran’s enriched uranium stockpile: Can it be safely transferred? - Al Jazeera    0.4939
Fri, 22 May 2026   İran                              CNN                              Iranian hackers are targeting aviation, oil and gas companies in espionage scheme, researchers say - CNN    0.0000
Thu, 21 May 2026   İran                       Al Jazeera                                                                           US-Iran diplomacy picks up: What’s the latest? - Al Jazeera    0.0000
Fri, 22 May 2026   İran                       Al Jazeera                                                               Iran war day 84: US-Iran talks advance amid mediation push - Al Jazeera   -0.5994
Fri, 22 May 2026   İran                              BBC                                                             US navy chief says $14bn arms sale to Taiwan paused due to Iran war - BBC   -0.5994
Sat, 23 May 2026   İran              The Times of Israel                                 Iran Talks Shift From Tehran to Beijing – NY to key UN Security Council Meeting - The Times of Israel    0.3400
Sat, 23 May 2026   İran  Radio Free Europe/Radio Liberty               From Tehran To Beijing, Pakistan Continues Diplomatic Push With Latest Iran War Talks - Radio Free Europe/Radio Liberty    0.4215
Thu, 21 May 2026   İran                     The Atlantic                                                                                           Trump’s Endgame Is Surrender - The Atlantic    0.0000
Thu, 21 May 2026   İran                              WSJ                                                                    House Republicans Pull Vote to Limit Trump’s Iran War Powers - WSJ   -0.5994
Thu, 21 May 2026   İran                 ایران اینترنشنال                                                                The strange afterlife of Iran’s firebrand president - ایران اینترنشنال   -0.2023
Thu, 21 May 2026   İran               The New York Times                                    Germany Charges Two Men With Plotting to Kill Jewish Leaders on Iran’s Behalf - The New York Times   -0.7783
Fri, 22 May 2026   İran                     The Guardian                           Qatar sends mediators to Tehran in sign talks to reopen strait of Hormuz are reaching climax - The Guardian    0.2023
Fri, 22 May 2026   İran                    Bloomberg.com                                                          Attack on UAE Nuclear Plant From Iraq ‘Warning Shot’ By Iran - Bloomberg.com   -0.4767
Sat, 23 May 2026   İran                  WyomingNews.com                                                Editorial: Congress should stop dodging its responsibilities on Iran - WyomingNews.com   -0.3818
Tue, 19 May 2026   İran               The New York Times                                        Early War Goal Was to Install Hard-Line Former President as Iran’s Leader - The New York Times   -0.5994
Sat, 23 May 2026   İran                         ynetnews                                                                   Explosive rift: US excludes Israel from Iran peace talks - ynetnews    0.5423
Sat, 23 May 2026   İran                      Daily Sabah                                         US weighs fresh attacks on Iran amid ongoing negotiations: Report | Daily Sabah - Daily Sabah   -0.1531

In [2]:
df

,ticker,source,title,compound,positive,negative,neutral
date,,,,,,,
"Sat, 23 May 2026",İran,Al Jazeera,Iran war live: Tehran says diplomacy continues...,-0.6428,0.000,0.288,0.712
"Sat, 23 May 2026",İran,The New York Times,"Once Trump’s Co-Pilot Against Iran, Netanyahu ...",0.0000,0.000,0.000,1.000
"Sat, 23 May 2026",İran,Fox News,Renewed US combat operations against Iran are ...,-0.3400,0.000,0.138,0.862
"Sat, 23 May 2026",İran,Sky News,Iran war latest: Trump says Iran war will be '...,-0.7906,0.106,0.346,0.548
"Sat, 23 May 2026",İran,The Times of Israel,Over 1.5 million pilgrims join Hajj despite fl...,-0.5520,0.151,0.243,0.606
...,...,...,...,...,...,...,...
"Tue, 19 May 2026",İran,The New York Times,Early War Goal Was to Install Hard-Line Former...,-0.5994,0.000,0.206,0.794
"Sat, 23 May 2026",İran,ynetnews,Explosive rift: US excludes Israel from Iran p...,0.5423,0.280,0.000,0.720
"Sat, 23 May 2026",İran,Daily Sabah,US weighs fresh attacks on Iran amid ongoing n...,-0.1531,0.134,0.169,0.698
"Sat, 23 May 2026",İran,Jefferson City News Tribune,Top Pakistani mediator in Iran amid hints of p...,0.7964,0.384,0.000,0.616
"Fri, 22 May 2026",İran,Bloomberg.com,The Key Sticking Points for a US-Iran Peace De...,0.5423,0.304,0.000,0.696

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk

nltk.download('vader_lexicon')

ticker = "İran"  # arama terimi olarak kullanılacak

# Google News RSS - tamamen ücretsiz, API yok
url = f"https://news.google.com/rss/search?q={ticker}&hl=en&gl=US&ceid=US:en"

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
response = requests.get(url, headers=headers)

parser = BeautifulSoup(response.text, "xml")
items = parser.find_all("item")

sia = SentimentIntensityAnalyzer()
sentiments = []

for item in items:
    title = item.find("title").text
    pub_date = item.find("pubDate").text[:16]  # tarih kısmı
    source = item.find("source").text if item.find("source") else "unknown"
    link = item.find("link").text

    score = sia.polarity_scores(title)

    sentiments.append({
        "ticker": ticker,
        "date": pub_date,
        "source": source,       # hangi haber sitesi
        "title": title,
        "compound": score["compound"],
        "positive": score["pos"],
        "negative": score["neg"],
        "neutral":  score["neu"]
    })

df = pd.DataFrame(sentiments)
df = df.set_index("date")

print(df[["ticker", "source", "title", "compound"]].to_string())

                 ticker                           source                                                                                                                                 title  compound
date
Sat, 23 May 2026   İran                       Al Jazeera                                                   Iran war live: Tehran says diplomacy continues but no deal yet with US - Al Jazeera   -0.6428
Sat, 23 May 2026   İran               The New York Times                                            Once Trump’s Co-Pilot Against Iran, Netanyahu Is Now a Mere Passenger - The New York Times    0.0000
Sat, 23 May 2026   İran                         Fox News                                 Renewed US combat operations against Iran are ‘matter of when,' former Navy commander says - Fox News   -0.3400
Sat, 23 May 2026   İran                         Sky News               Iran war latest: Trump says Iran war will be 'over with soon' - as US national intelligence director resigns - Sky News   -0.7906
Sat, 23 May 2026   İran              The Times of Israel  Over 1.5 million pilgrims join Hajj despite flight disruptions from Iran war, Tehran's attacks on Saudi Arabia - The Times of Israel   -0.5520
Sat, 23 May 2026   İran                              WSJ                                                                  How the War in Iran Helped Ukraine Go From Problem to Solution - WSJ   -0.6486
Sat, 23 May 2026   İran                              CNN                                                    Trump meets with national security officials as he weighs next steps on Iran - CNN    0.3400
Fri, 22 May 2026   İran                         CBS News                                                                        U.S. prepares for new military strikes against Iran - CBS News   -0.3612
Sat, 23 May 2026   İran                              BBC                                                              Marco Rubio visits India to sell energy as Iran oil shock persists - BBC   -0.1280
Sat, 23 May 2026   İran                          Reuters                                                                              Three months in, is Trump losing the Iran war? - Reuters   -0.7579
Fri, 22 May 2026   İran   Institute for the Study of War                                                             Iran Update Special Report, May 22, 2026 - Institute for the Study of War   -0.2960
Sat, 23 May 2026   İran                 ایران اینترنشنال                                    Live - Iran downplays deal hopes as Pakistan pushes talks and US weighs strikes - ایران اینترنشنال    0.0772
Sat, 23 May 2026   İran               The New York Times                                                       The Risks of Iran’s Threat to Control the Strait of Hormuz - The New York Times   -0.6705
Sat, 23 May 2026   İran                         The Week                                                                                The war with Iran: stalemate, or checkmate? - The Week   -0.5994
Sat, 23 May 2026   İran               The Jerusalem Post                                                          Live Updates: Latest from Israel, Iran, and Middle East - The Jerusalem Post    0.0000
Sat, 23 May 2026   İran                     The Guardian               An ever-expanding catastrophe over Iran is not inevitable. Trump can and must be stopped | Simon Tisdall - The Guardian   -0.7430
Fri, 22 May 2026   İran                              WSJ                                                                                     Opinion | Don’t Leave the Iran War Half-Won - WSJ   -0.6249
Sat, 23 May 2026   İran                       Al Jazeera                                                               Iran war day 85: Tehran says major gaps remain in US talks - Al Jazeera   -0.5994
Sat, 23 May 2026   İran                 ایران اینترنشنال                                                          Hope for US-Iran deal faces hardliner hostility in Tehran - ایران اینترنشنال   -0.1531
Sat, 23 May 2026   İran               The New York Times                                                             Regional Mediators Rush to Save U.S.-Iran Cease-Fire - The New York Times    0.4939
Sat, 23 May 2026   İran               The New York Times                                                     Trump Weighs His Options in Carrying Out New Strikes in Iran - The New York Times   -0.3612
Fri, 22 May 2026   İran                              PBS                                        U.S. says 'slight progress' in Iran talks amid uncertainty about whether war will resume - PBS   -0.5423
Sat, 23 May 2026   İran                       Al Jazeera                                               Iran weighs US peace proposal despite ‘deep and significant’ disagreements - Al Jazeera    0.1779
Sat, 23 May 2026   İran                    Bloomberg.com                                                                           What If the Strait of Hormuz Didn’t Reopen? - Bloomberg.com    0.0000
Sat, 23 May 2026   İran               Hasht-e Subh Daily                                                                Iran–US Tensions; Asim Munir meets Abbas Araghchi - Hasht-e Subh Daily   -0.4019
Sat, 23 May 2026   İran                              WSJ                                                   Iran Moved Billions Through Binance to Fund Regime—Continuing Into This Month - WSJ    0.0000
Fri, 22 May 2026   İran                            Axios                                                                     Trump met top advisers on Iran as he weighs return to war - Axios   -0.4767
Fri, 22 May 2026   İran                            Axios                                                               Pakistani field marshal in Tehran to try to seal U.S.-Iran deal - Axios    0.0000
Fri, 22 May 2026   İran                       Al Jazeera                                                             Economic confidence plummets in US amid Iran war, poll shows - Al Jazeera   -0.1531
Sat, 23 May 2026   İran                          Reuters                                                                  US arms sales to Taiwan unrelated to Iran war, source says - Reuters   -0.5994
Sat, 23 May 2026   İran              The Times of Israel                              Trump reportedly moving toward ordering strikes on Iran but no final decision made - The Times of Israel   -0.5499
Fri, 22 May 2026   İran                          AP News                            Rubio reports 'slight progress' in Iran talks as Pakistan renews efforts to mediate a peace deal - AP News    0.7430
Sat, 23 May 2026   İran                          Reuters                                                           Indian retailers raise fuel prices for a third time amid Iran war - Reuters   -0.5994
Sat, 23 May 2026   İran                   Anadolu Ajansı                                      US weighs renewed military action against Iran as negotiations continue: Report - Anadolu Ajansı    0.0000
Thu, 21 May 2026   İran   Institute for the Study of War                                                             Iran Update Special Report, May 21, 2026 - Institute for the Study of War   -0.2960
Fri, 22 May 2026   İran               The Jerusalem Post                No deal in sight if US insists on discussing nuclear issue, Iranian FM spokesperson says - report - The Jerusalem Post   -0.2960
Thu, 21 May 2026   İran     Council on Foreign Relations                                 Iran’s War With Israel and the United States | Global Conflict Tracker - Council on Foreign Relations   -0.5267
Thu, 21 May 2026   İran                              WSJ                                                                             Opinion | The Iran War and the Anti-American Reflex - WSJ   -0.5994
Fri, 22 May 2026   İran                          Reuters                     Exclusive: Qatari negotiating team in Tehran to try to help secure US-Iran deal to end war, says source - Reuters    0.1779
Sat, 23 May 2026   İran                   Anadolu Ajansı                                              Iranian top diplomat, Pakistan army chief discuss US-Iran peace efforts - Anadolu Ajansı    0.6486
Fri, 22 May 2026   İran                       Al Jazeera                                              Pakistan’s army chief in Iran as US’s Rubio says ‘slight progress’ in talks - Al Jazeera    0.0000
Fri, 22 May 2026   İran                          Reuters                                             Iran's intensified closure of Strait of Hormuz piles misery on stranded sailors - Reuters   -0.5719
Fri, 22 May 2026   İran                         ynetnews                                        Last-ditch push before war? Iran talks near collapse as Trump weighs a final strike - ynetnews   -0.8225
Sat, 23 May 2026   İran                 RealClearDefense                                                                                   Don’t Repeat Afghanistan in Iran - RealClearDefense    0.0000
Fri, 22 May 2026   İran                         The Hill                                                                    Iran, Oman discuss Strait of Hormuz toll system: Report - The Hill    0.0000
Thu, 21 May 2026   İran                         CBS News                             Iran says it's mulling latest U.S. peace proposal and Trump says he'll wait "a couple of days" - CBS News    0.5423
Fri, 22 May 2026   İran                          AP News                                Photos of live music stirring back to life in Tehran as a ceasefire offers a fragile respite - AP News    0.0000
Fri, 22 May 2026   İran                              WSJ                                                             The Oil Mystery at the Heart of America’s Pressure Campaign on Iran - WSJ   -0.2960
Sat, 23 May 2026   İran                    Bloomberg.com                                                           Iran Peace Deal Push Intensifies as Fragile Ceasefire Holds - Bloomberg.com    0.5423
Fri, 22 May 2026   İran                         Fox News                                               Top Republican warns Trump against making a deal with Iran: 'Finish the job' - Fox News    0.1027
Fri, 22 May 2026   İran                             CNBC                            U.S., Iran signal peace progress — but remain at odds over enriched uranium, Strait of Hormuz tolls - CNBC    0.4854
Fri, 22 May 2026   İran                         ynetnews                                                              Report: 'Trump administration preparing to strike Iran again' - ynetnews   -0.1280
Thu, 21 May 2026   İran                         NBC News                              Iran-U.S. diplomacy intensifies as Trump seeks ‘right answers,’ Tehran signals gaps ‘reduced’ - NBC News    0.0000
Thu, 21 May 2026   İran                    economist.com                                                                 Donald Trump is still looking for a quick fix in Iran - economist.com    0.0000
Fri, 22 May 2026   İran              The Times of Israel                           Qatari team in Tehran for talks; Trump says skipping son’s wedding to stay in capital - The Times of Israel    0.0000
Fri, 22 May 2026   İran                         The Hill                                       Wicker warns Trump against ‘ill advised’ Iran deal: ‘We must finish what we started’ - The Hill   -0.1027
Fri, 22 May 2026   İran               The New York Times                                                      Asian Currencies Hit by Iran War, Adding to Economic Strain - The New York Times   -0.6249
Thu, 21 May 2026   İran                          Reuters                                      Exclusive: Supreme Leader says enriched uranium must stay in Iran, Iranian sources say - Reuters    0.6249
Fri, 22 May 2026   İran                         NBC News                                                                        House Republicans cancel vote curbing Trump on Iran - NBC News   -0.2500
Fri, 22 May 2026   İran                  Middle East Eye                                                   Iran destroyed 20 percent of US's MQ-9 Reaper drone fleet: Report - Middle East Eye   -0.4939
Sat, 23 May 2026   İran        Robin J Brooks | Substack                                                                   The US Blockade of Iran after Six Weeks - Robin J Brooks | Substack    0.0000
Fri, 22 May 2026   İran                         CBS News                                                 Gabbard resignation comes as Trump may be considering relaunching Iran war - CBS News   -0.7269
Sat, 23 May 2026   İran                           DW.com                                                                          US or Iran: Who will win the Hormuz endurance game? - DW.com    0.5859
Sat, 23 May 2026   İran                 ایران اینترنشنال                                                      Iran cleric says hijab should not divide wartime mobilization - ایران اینترنشنال    0.0000
Fri, 22 May 2026   İran                          Reuters                                               US Secretary of State Rubio sees progress in Iran talks, more work to be done - Reuters    0.4215
Fri, 22 May 2026   İran                              NPR                                               Republicans call off vote on Iran war resolution that was on the verge of passing - NPR   -0.5994
Fri, 22 May 2026   İran              The Washington Post                                          Opinion | I did something AI never could: Make my calculus teacher cry - The Washington Post   -0.4767
Fri, 22 May 2026   İran                              PBS                                                                          Is it time for the U.S. to reassess its Iran strategy? - PBS    0.0000
Fri, 22 May 2026   İran                             CNBC                                                     Oil prices post weekly loss as U.S. and Iran signal progress toward a deal - CNBC    0.1280
Fri, 22 May 2026   İran                             CNBC                                            Consumer sentiment hits fresh record low in May as Iran war fuels inflation worries - CNBC   -0.7579
Thu, 21 May 2026   İran               The New York Times                                      GOP Pulls Measure on Trump’s War Powers in Iran, Lacking Votes to Defeat It - The New York Times   -0.7845
Sat, 23 May 2026   İran                        France 24                                                                        War in the Middle East: US-Iran talks make headway - France 24   -0.5994
Fri, 22 May 2026   İran               The New York Times                                                 Iran and Oman in Talks Over Strait of Hormuz Ship Payment System - The New York Times    0.0000
Fri, 22 May 2026   İran                         The Hill                                                                              Bolton pushes for Trump to end Iran ceasefire - The Hill    0.0000
Sat, 23 May 2026   İran               The Jerusalem Post                Iran, Oman negotiate possible tolls system for Strait of Hormuz even as US warns against it - NYT - The Jerusalem Post   -0.1027
Sat, 23 May 2026   İran                    Bloomberg.com                                                          Arab Nations Seek Iran War Deal as Ceasefire Remains Fragile - Bloomberg.com   -0.5994
Fri, 22 May 2026   İran                        France 24                                                            Rubio urges more support from NATO allies to help end Iran war - France 24    0.2006
Thu, 21 May 2026   İran                             CNBC                                                                           Oil prices fall as investors hope for U.S.-Iran deal - CNBC    0.4404
Fri, 22 May 2026   İran                    Bloomberg.com                                                            UAE Joins Saudis, Qatar in Urging Trump Not to Restart War - Bloomberg.com    0.4847
Sat, 23 May 2026   İran                           Forbes                                                         Trump’s Approval Rating Declines In 4 Polls This Week, Improves In 1 - Forbes    0.7096
Thu, 21 May 2026   İran                              BBC                                                           Strait of Hormuz: Iran steps up claim to control Middle East waterway - BBC    0.0000
Fri, 22 May 2026   İran                       Al Jazeera                                                         Iran’s enriched uranium stockpile: Can it be safely transferred? - Al Jazeera    0.4939
Fri, 22 May 2026   İran                              CNN                              Iranian hackers are targeting aviation, oil and gas companies in espionage scheme, researchers say - CNN    0.0000
Thu, 21 May 2026   İran                       Al Jazeera                                                                           US-Iran diplomacy picks up: What’s the latest? - Al Jazeera    0.0000
Fri, 22 May 2026   İran                       Al Jazeera                                                               Iran war day 84: US-Iran talks advance amid mediation push - Al Jazeera   -0.5994
Fri, 22 May 2026   İran                              BBC                                                             US navy chief says $14bn arms sale to Taiwan paused due to Iran war - BBC   -0.5994
Sat, 23 May 2026   İran              The Times of Israel                                 Iran Talks Shift From Tehran to Beijing – NY to key UN Security Council Meeting - The Times of Israel    0.3400
Sat, 23 May 2026   İran  Radio Free Europe/Radio Liberty               From Tehran To Beijing, Pakistan Continues Diplomatic Push With Latest Iran War Talks - Radio Free Europe/Radio Liberty    0.4215
Thu, 21 May 2026   İran                     The Atlantic                                                                                           Trump’s Endgame Is Surrender - The Atlantic    0.0000
Thu, 21 May 2026   İran                              WSJ                                                                    House Republicans Pull Vote to Limit Trump’s Iran War Powers - WSJ   -0.5994
Thu, 21 May 2026   İran                 ایران اینترنشنال                                                                The strange afterlife of Iran’s firebrand president - ایران اینترنشنال   -0.2023
Thu, 21 May 2026   İran               The New York Times                                    Germany Charges Two Men With Plotting to Kill Jewish Leaders on Iran’s Behalf - The New York Times   -0.7783
Fri, 22 May 2026   İran                     The Guardian                           Qatar sends mediators to Tehran in sign talks to reopen strait of Hormuz are reaching climax - The Guardian    0.2023
Fri, 22 May 2026   İran                    Bloomberg.com                                                          Attack on UAE Nuclear Plant From Iraq ‘Warning Shot’ By Iran - Bloomberg.com   -0.4767
Sat, 23 May 2026   İran                  WyomingNews.com                                                Editorial: Congress should stop dodging its responsibilities on Iran - WyomingNews.com   -0.3818
Tue, 19 May 2026   İran               The New York Times                                        Early War Goal Was to Install Hard-Line Former President as Iran’s Leader - The New York Times   -0.5994
Sat, 23 May 2026   İran                         ynetnews                                                                   Explosive rift: US excludes Israel from Iran peace talks - ynetnews    0.5423
Sat, 23 May 2026   İran                      Daily Sabah                                         US weighs fresh attacks on Iran amid ongoing negotiations: Report | Daily Sabah - Daily Sabah   -0.1531

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
compound,100.0,-0.143705,0.434530,-0.8225,-0.578775,-0.11535,0.083575,0.7964
positive,100.0,0.079900,0.112342,0.0000,0.000000,0.00000,0.153000,0.3960
negative,100.0,0.141320,0.135843,0.0000,0.000000,0.15400,0.237750,0.4590
neutral,100.0,0.778790,0.148783,0.4980,0.689500,0.76100,0.894250,1.0000